# DQ1. All diseases with their parents (identified by label)
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?id ?label ?parent
WHERE {
    ?class a owl:Class .
    ?class oboInOwl:id ?id .
    ?class rdfs:label ?label .
    ?class rdfs:subClassOf ?parent_class .

    ?parent_class rdfs:label ?parent .
}