# DQ5. Diseases with MeSH cross-references
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?id ?label (GROUP_CONCAT(?xref; separator="|") AS ?mesh_xref)
WHERE {
    ?class oboInOwl:id ?id ;
		rdfs:label ?label ;
        oboInOwl:hasDbXref ?xref .
    FILTER( STRSTARTS( STR(?xref), "MESH:" ) )
}
GROUP BY ?id ?label
ORDER BY ?id