#id: DOq043
#description: Get information about graphs (ontology datasets) in DO's SPARQL endpoint
#input: [doid.owl, doid-merged.owl]
#comment: The default graph is doid.owl. FROM statements are required to query
#  other graphs or more than one graph.
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT *
FROM <http://purl.obolibrary.org/obo/doid.owl>
FROM <http://purl.obolibrary.org/obo/doid/doid-merged.owl>
WHERE {
  VALUES ?graph {
    <http://purl.obolibrary.org/obo/doid.owl> # default graph
    <http://purl.obolibrary.org/obo/doid/doid-merged.owl>
  }

  ?graph ?pred ?obj
}