#id: DOq042
#description: List the graphs included in the SPARQL database
#input:
#comment: >-
#  Should work for other SPARQL databases (with added SERVICE statement to
#  specify the endpoint).
SELECT DISTINCT ?graph
WHERE {
  GRAPH ?graph { ?s ?p ?o }
}