#id: DOq003
#description: >-
#  Count of diseases in each branch (diseases may be in multiple branches)
#input: doid.owl
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?branch (COUNT(DISTINCT ?iri) AS ?count)
WHERE {
  ?iri rdfs:subClassOf* ?branch_iri .
  ?branch_iri rdfs:subClassOf obo:DOID_4 ;
    rdfs:label ?branch .
}
GROUP BY ?branch
ORDER BY ?branch