#id: DOq052
#description: >-
#  Count of language tags used for class annotations, by class namespace and
#  annotation property
#input: []
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?type
WHERE {
  ?iri a owl:Class ;
    ?annotation ?literal .
  ?annotation a owl:AnnotationProperty .
  FILTER(isLiteral(?literal))
  BIND(LANG(?literal) AS ?lang)
  BIND(REPLACE(str(?iri), ".*/([^#_]+).*", "$1") AS ?namespace)
}
